# gen_verify.rb <d64> <out.asm> [count] - emit the expected-checksum table that
# test/flverify.asm compares the fast loader against. Spreading the sectors
# across the disk is the point: a single sector read twice proves only that the
# loader is deterministic, not that it fetched the sector that was asked for.
require_relative "d64"
img, out, count = ARGV[0], ARGV[1], (ARGV[2] || 200).to_i
disk = File.binread(img)
sectors_per_track = ->(t) { t <= 17 ? 21 : t <= 24 ? 19 : t <= 30 ? 18 : 17 }
list = []
(1..35).each do |t|
  next if t == 18                       # directory track, no story data
  (0...sectors_per_track.(t)).each { |s| list << [t, s] }
end
# Walk the disk in strides so the head has to seek, not just step.
picked = (0...count).map { |i| list[(i * 37) % list.size] }
File.open(out, "w") do |f|
  f.puts "; generated by tools/fastloader/gen_verify.rb from #{File.basename(img)}"
  f.puts "NSECTORS = #{picked.size}"
  f.puts "tracks"
  picked.each_slice(16) { |g| f.puts "\t!byte " + g.map { |t, _| t }.join(",") }
  f.puts "sectors"
  picked.each_slice(16) { |g| f.puts "\t!byte " + g.map { |_, s| s }.join(",") }
  # Two byte tables, not one word table: with up to 255 entries a word table
  # would need a 16-bit index, and "asl" on an 8-bit index silently wraps.
  sums = picked.map { |t, s| disk[d64_track_offset(t, s), 256].bytes.sum & 0xffff }
  f.puts "cksums_lo"
  sums.each_slice(16) { |g| f.puts "\t!byte " + g.map { |c| c & 0xff }.join(",") }
  f.puts "cksums_hi"
  sums.each_slice(16) { |g| f.puts "\t!byte " + g.map { |c| c >> 8 }.join(",") }
end
puts "#{out}: #{picked.size} sectors"
