all: zork1 minizork hollywood

minizork:
	../create_d64.rb minizork.z3 minizork.d64

zork1:
	../create_d64.rb zork1.z3 zork1.d64

hollywood:
	../create_d64.rb hollywood.z3 hollywood.d64

clean:
	rm -f *.d64

