#!/usr/bin/python3
"""Convert a directory of numbered PNGs into an ACME source file that Ozmoo
assembles into the interpreter.

    python3 tools/pics2asm.py temp/pictures.asm tools/testpics

Each <n>.png becomes picture number n. This is the first, small-scale form of
the picture pipeline: the data is embedded in the binary. Arthur's set is far
too large for that and will be preloaded into attic RAM instead, but the tile
format, the cell map and the palette layout are the same either way.

See tools/png2fcm.py for the format's reasoning. In short: FCM cells are 8x8
pixels, one byte per pixel, 64 bytes per cell; pixel 0 is transparent and 255
comes from colour RAM, so a picture's colours live in palette entries 16..31 and
its pixel indices are offset to match. draw_picture shifts them again, by 16 per
window, so each of the eight windows has its own bank. Identical cells are
stored once.
"""
import os, sys, glob
from PIL import Image

BASE = 16

def nybswap(v):
    return ((v & 0x0F) << 4) | (v >> 4)

def convert(path, palette_base=BASE):
    im = Image.open(path)
    if im.mode != "P":
        sys.exit(f"{path}: not an indexed PNG")
    w, h = im.size
    pal = im.getpalette()
    used = sorted({i for _, i in im.getcolors()})
    if len(used) > 16:
        sys.exit(f"{path}: {len(used)} colours, more than one palette bank holds")
    remap = {old: palette_base + n for n, old in enumerate(used)}
    colours = [tuple(pal[o*3:o*3+3]) for o in used]

    cw, ch = (w + 7) // 8, (h + 7) // 8
    px = im.load()
    tiles, index_of, cellmap = bytearray(), {}, []
    for cy in range(ch):
        for cx in range(cw):
            cell = bytes(remap[px[cx*8+c, cy*8+r]]
                         if cx*8+c < w and cy*8+r < h else 0
                         for r in range(8) for c in range(8))
            if cell not in index_of:
                index_of[cell] = len(index_of)
                tiles += cell
            cellmap.append(index_of[cell])
    if len(index_of) > 256:
        sys.exit(f"{path}: {len(index_of)} unique tiles; the cell map here is "
                 f"one byte per cell. Arthur's pictures need the 16 bit map "
                 f"that png2fcm.py emits, and attic RAM to hold the tiles.")

    palette = bytearray(48)
    for chan in range(3):
        for n in range(16):
            v = colours[n][chan] if n < len(colours) else 0
            palette[chan*16 + n] = nybswap(v)
    return dict(w=w, h=h, cw=cw, ch=ch, tiles=bytes(tiles),
                ntiles=len(index_of), map=cellmap, pal=bytes(palette))

def bytes_asm(name, data, per=16):
    out = [f"{name}"]
    for i in range(0, len(data), per):
        out.append("\t!byte " + ",".join(f"${b:02x}" for b in data[i:i+per]))
    return "\n".join(out)

def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <out.asm> <png-dir>")
    out, pngdir = sys.argv[1], sys.argv[2]

    files = sorted(glob.glob(os.path.join(pngdir, "*.png")),
                   key=lambda s: int(os.path.basename(s)[:-4]))
    if not files:
        sys.exit(f"no numbered PNGs in {pngdir}")
    pics = []
    tile_base = 0
    for n, path in enumerate(files):
        num = int(os.path.basename(path)[:-4])
        p = convert(path)
        p['tile_base'] = tile_base
        tile_base += p['ntiles']
        pics.append((num, p))
    if tile_base > 1024:
        sys.exit(f"{tile_base} tiles = {tile_base*64//1024} KB: bank 1 holds 1024 "
                 f"tiles (64 KB). Arthur's set needs attic RAM and one picture "
                 f"resident at a time.")

    L = []
    L.append("; Generated by tools/pics2asm.py - do not edit")
    L.append(f"; from {pngdir}: " + ", ".join(str(n) for n, _ in pics))
    L.append(";")
    L.append("; Every picture has its own run of tiles in the store. Pixel indices are")
    L.append("; relative to palette entry 16; draw_picture shifts them into the")
    L.append("; drawing window's own bank of 16, because a window holds at most")
    L.append("; one picture, so eight banks above the text colours are enough.")
    L.append("")
    L.append(f"picture_count = {len(pics)}")
    L.append(f"picture_total_tiles = {tile_base}")
    L.append("")
    L.append("pic_number\t!byte " + ",".join(str(n) for n, _ in pics))
    L.append("pic_cells_w\t!byte " + ",".join(str(p['cw']) for _, p in pics))
    L.append("pic_cells_h\t!byte " + ",".join(str(p['ch']) for _, p in pics))
    L.append("pic_map_lo\t!byte " + ",".join(f"<pic{n}_map" for n, _ in pics))
    L.append("pic_map_hi\t!byte " + ",".join(f">pic{n}_map" for n, _ in pics))
    L.append("pic_data_lo\t!byte " + ",".join(f"<pic{n}_data" for n, _ in pics))
    L.append("pic_data_hi\t!byte " + ",".join(f">pic{n}_data" for n, _ in pics))
    L.append("pic_pal_lo\t!byte " + ",".join(f"<pic{n}_pal" for n, _ in pics))
    L.append("pic_pal_hi\t!byte " + ",".join(f">pic{n}_pal" for n, _ in pics))
    L.append("pic_tiles\t!byte " + ",".join(str(p['ntiles']) for _, p in pics))
    L.append("; where each picture's tiles sit in the store")
    L.append("pic_tile_base\t!byte " + ",".join(str(p['tile_base']) for _, p in pics))
    L.append("")
    for n, p in pics:
        L.append(f"; picture {n}: {p['w']}x{p['h']} px, {p['cw']}x{p['ch']} cells,"
                 f" {p['ntiles']} tiles from {p['tile_base']},"
                 f" palette {BASE + 16*[i for i,(m,_) in enumerate(pics) if m==n][0]}")
    L.append("")
    # the cell maps hold the full 16-bit screen code: tile address / 64
    for n, p in pics:
        codes = [1024 + p['tile_base'] + i for i in p['map']]
        L.append(bytes_asm(f"pic{n}_map", bytes([c & 0xff for c in codes]
                                                + [c >> 8 for c in codes])))
    L.append("")
    for n, p in pics:
        L.append(bytes_asm(f"pic{n}_pal", p['pal']))
    L.append("")
    for n, p in pics:
        L.append(bytes_asm(f"pic{n}_data", p['tiles']))
    L.append("")

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    open(out, "w").write("\n".join(L) + "\n")
    print(f"{out}: {len(pics)} pictures, {tile_base} tiles "
          f"({tile_base*64} bytes), {len(pics)*48} bytes of palette")

main()
