#!/usr/bin/python3
"""Convert a directory of numbered PNGs into MEGA65 picture files.

    python3 tools/pics2asm.py temp tools/testpics

Writes, into <outdir>:
    pictures.asm    the index Ozmoo assembles in: how many pictures there are
                    and what they are numbered. Nothing else is embedded.
    p<nnn>.bin      one file per picture, which make.rb puts on the d81 and
                    Ozmoo preloads into attic RAM at boot, the way it already
                    preloads the sound effects.

A picture file is:
    0       cells wide
    1       cells high
    2..3    number of unique tiles, little endian
    4..51   palette: 16 red, then 16 green, then 16 blue, nybble swapped as the
            VIC-IV palette registers want
    52..    the cell map: two bytes a cell, row major, a little endian index
            into the tiles below
    then    the tiles: 64 bytes each, one byte a pixel

FCM cells are 8x8 pixels and a cell's screen code is its data address divided by
64. Pixel 0 is transparent and 255 comes from colour RAM, so a picture's colours
are written relative to palette entry 16, and draw_picture shifts them again by
16 per window: a window holds at most one picture, so the eight banks above the
16 text colours are enough for any number of pictures.
"""
import os, sys, glob, struct
from PIL import Image

BASE = 16

def nybswap(v):
    return ((v & 0x0F) << 4) | (v >> 4)

def convert(path):
    im = Image.open(path)
    if im.mode != "P":
        sys.exit(f"{path}: not an indexed PNG")
    w, h = im.size
    pal = im.getpalette()
    used = sorted({i for _, i in im.getcolors()})
    if len(used) > 16:
        sys.exit(f"{path}: {len(used)} colours, more than one palette bank holds")
    remap = {old: BASE + n for n, old in enumerate(used)}
    colours = [tuple(pal[o*3:o*3+3]) for o in used]

    cw, ch = (w + 7) // 8, (h + 7) // 8
    if cw > 40 or ch > 25:
        sys.exit(f"{path}: {cw}x{ch} cells, larger than the 40x25 screen")
    px = im.load()
    tiles, index_of, cellmap = bytearray(), {}, []
    for cy in range(ch):
        for cx in range(cw):
            cell = bytes(remap[px[cx*8+c, cy*8+r]]
                         if cx*8+c < w and cy*8+r < h else 0
                         for r in range(8) for c in range(8))
            if cell not in index_of:
                index_of[cell] = len(index_of)
                tiles += cell
            cellmap.append(index_of[cell])

    ntiles = len(index_of)
    if ntiles > 1024:
        sys.exit(f"{path}: {ntiles} unique tiles; the store in bank 1 holds 1024")

    palette = bytearray(48)
    for chan in range(3):
        for n in range(16):
            v = colours[n][chan] if n < len(colours) else 0
            palette[chan*16 + n] = nybswap(v)

    blob = bytearray()
    blob += bytes((cw, ch))
    blob += struct.pack("<H", ntiles)
    blob += palette
    for i in cellmap:
        blob += struct.pack("<H", i)
    blob += tiles
    if len(blob) > 255 * 256:
        sys.exit(f"{path}: {len(blob)} bytes; a file preloaded into attic may be "
                 f"at most 255 pages, because m65_load_file_to_reu counts pages "
                 f"in one byte")
    return dict(w=w, h=h, cw=cw, ch=ch, ntiles=ntiles,
                colours=len(used), blob=bytes(blob))

def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <outdir> <png-dir>")
    outdir, pngdir = sys.argv[1], sys.argv[2]

    files = sorted(glob.glob(os.path.join(pngdir, "*.png")),
                   key=lambda s: int(os.path.basename(s)[:-4]))
    if not files:
        sys.exit(f"no numbered PNGs in {pngdir}")

    os.makedirs(outdir, exist_ok=True)
    nums, total = [], 0
    for path in files:
        num = int(os.path.basename(path)[:-4])
        if not 0 < num < 256:
            sys.exit(f"{path}: picture numbers must be 1..255")
        p = convert(path)
        open(os.path.join(outdir, f"p{num:03d}.bin"), "wb").write(p['blob'])
        nums.append(num)
        total += len(p['blob'])
        print(f"  picture {num:3d}: {p['w']}x{p['h']} px, {p['cw']}x{p['ch']} cells, "
              f"{p['ntiles']} tiles, {p['colours']} colours, {len(p['blob'])} bytes")

    with open(os.path.join(outdir, "pictures.asm"), "w") as f:
        f.write("; Generated by tools/pics2asm.py - do not edit\n")
        f.write(f"; from {pngdir}\n;\n")
        f.write("; Only the index is assembled in. Each picture is a file on the\n")
        f.write("; disk, preloaded into attic RAM at boot.\n\n")
        f.write(f"picture_count = {len(nums)}\n\n")
        f.write("pic_number\t!byte " + ",".join(str(n) for n in nums) + "\n")
        f.write("pic_page_lo\t!fill picture_count, 0\n")
        f.write("pic_page_hi\t!fill picture_count, 0\n")

    print(f"{len(nums)} pictures, {total} bytes on disk")

main()
